import React, { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Send, Key, Coins, ShieldAlert, CheckCircle, ArrowLeft, Smartphone,
  QrCode, Copy, Download, CheckCheck, ScanLine, X, Camera, Clock,
} from 'lucide-react';
import { meshApi } from '../services/meshApi';
import toast from 'react-hot-toast';
import QRCode from 'qrcode';
import { Input } from '../components/ui/Input';
import { Select } from '../components/ui/Select';
import { Button } from '../components/ui/Button';
import { staggerContainer, listItem, fadeInRight } from '../utils/motionConfig';

// ─── Types ───────────────────────────────────────────────

interface PacketResult {
  packetId: string;
  ciphertextPreview: string;
  injectedAt: string;
  ttl: number;
}

interface PaymentInfo {
  senderVpa: string;
  receiverVpa: string;
  amount: number;
  packetId: string;
}

// ─── Helpers ─────────────────────────────────────────────

function formatAmount(n: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(n);
}

function generateReceipt(info: PaymentInfo, packet: PacketResult): string {
  const now = new Date().toISOString().replace('T', ' ').slice(0, 19);
  return [
    '═══════════════════════════════════════',
    '     MESH NETWORK PAYMENT RECEIPT     ',
    '═══════════════════════════════════════',
    '',
    `  Date:       ${now}`,
    `  Amount:     ${formatAmount(info.amount)}`,
    `  Sender:     ${info.senderVpa}`,
    `  Receiver:   ${info.receiverVpa}`,
    `  TX ID:      ${info.packetId}`,
    `  TTL:        ${packet.ttl} hops`,
    `  Injected:   ${packet.injectedAt}`,
    '',
    '───────────────────────────────────────',
    '  Status: PENDING (in mesh gossip)    ',
    '───────────────────────────────────────',
    '',
    '  Ciphertext:',
    `  ${packet.ciphertextPreview}`,
    '',
    '═══════════════════════════════════════',
    '  Generated by Mesh Network Simulator ',
    '═══════════════════════════════════════',
  ].join('\n');
}

const VPA_OPTIONS = [
  { value: 'alice@demo', label: 'Alice Johnson (alice@demo)' },
  { value: 'bob@demo', label: 'Bob Smith (bob@demo)' },
  { value: 'carol@demo', label: 'Carol White (carol@demo)' },
  { value: 'dave@demo', label: 'Dave Miller (dave@demo)' },
];

// ─── Component ──────────────────────────────────────────

export const SendPayment: React.FC = () => {
  const [senderVpa, setSenderVpa] = useState('alice@demo');
  const [receiverVpa, setReceiverVpa] = useState('bob@demo');
  const [amount, setAmount] = useState('500');
  const [pin, setPin] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [generatedPacket, setGeneratedPacket] = useState<PacketResult | null>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [showScanner, setShowScanner] = useState(false);
  const [scanProgress, setScanProgress] = useState(0);
  const [scanComplete, setScanComplete] = useState(false);
  const [showConfirmation, setShowConfirmation] = useState(false);
  const scanTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    return () => {
      if (scanTimerRef.current) clearInterval(scanTimerRef.current);
    };
  }, []);

  const generateQR = useCallback(async (info: PaymentInfo, packet: PacketResult) => {
    try {
      const qrPayload = JSON.stringify({
        type: 'UPI_PAYMENT',
        version: '1.0',
        packetId: info.packetId,
        senderVpa: info.senderVpa,
        receiverVpa: info.receiverVpa,
        amount: info.amount,
        injectedAt: packet.injectedAt,
      });
      const url = await QRCode.toDataURL(qrPayload, {
        width: 280,
        margin: 2,
        color: { dark: '#202532', light: '#ffffff' },
      });
      setQrDataUrl(url);
    } catch {
      // QR generation failed silently
    }
  }, []);

  const handleInject = async (e: React.FormEvent) => {
    e.preventDefault();

    const parsedAmount = parseFloat(amount);
    if (!amount || parsedAmount <= 0) {
      toast.error('Amount must be positive');
      return;
    }

    if (senderVpa === receiverVpa) {
      toast.error('Sender and receiver VPAs must be different');
      return;
    }

    if (!pin || pin.length < 4) {
      toast.error('PIN must be at least 4 characters');
      return;
    }

    setIsSubmitting(true);

    try {
      const result = await meshApi.injectPacket({
        senderVpa,
        receiverVpa,
        amount: parsedAmount,
        pin,
      });

      const packet = {
        packetId: result.packetId,
        ciphertextPreview: result.ciphertextPreview,
        injectedAt: result.injectedAt,
        ttl: result.ttl,
      };
      setGeneratedPacket(packet);
      setShowConfirmation(false);
      setQrDataUrl(null);

      const info: PaymentInfo = {
        senderVpa,
        receiverVpa,
        amount: parsedAmount,
        packetId: result.packetId,
      };
      generateQR(info, packet);

      toast.success(`Packet ${result.packetId} injected at ${result.injectedAt}`);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to inject packet';
      toast.error(message);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleResetForm = () => {
    setGeneratedPacket(null);
    setQrDataUrl(null);
    setShowConfirmation(false);
    setShowScanner(false);
    setScanComplete(false);
    setScanProgress(0);
    setAmount('500');
    setPin('');
  };

  const handleSimulateScan = () => {
    setShowScanner(true);
    setScanProgress(0);
    setScanComplete(false);
    setShowConfirmation(false);

    const duration = 2400;
    const interval = 40;
    const step = 100 / (duration / interval);

    scanTimerRef.current = setInterval(() => {
      setScanProgress(prev => {
        const next = prev + step;
        if (next >= 100) {
          if (scanTimerRef.current) clearInterval(scanTimerRef.current);
          scanTimerRef.current = null;
          setScanProgress(100);
          setScanComplete(true);
          setTimeout(() => {
            setShowScanner(false);
            setShowConfirmation(true);
          }, 600);
          return 100;
        }
        return next;
      });
    }, interval);
  };

  const handleCancelScan = () => {
    if (scanTimerRef.current) clearInterval(scanTimerRef.current);
    scanTimerRef.current = null;
    setShowScanner(false);
    setScanProgress(0);
    setScanComplete(false);
  };

  const handleCopyTxId = async () => {
    if (!generatedPacket) return;
    try {
      await navigator.clipboard.writeText(generatedPacket.packetId);
      setCopied(true);
      toast.success('Transaction ID copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy to clipboard');
    }
  };

  const handleDownloadReceipt = () => {
    if (!generatedPacket) return;
    const info: PaymentInfo = {
      senderVpa,
      receiverVpa,
      amount: parseFloat(amount),
      packetId: generatedPacket.packetId,
    };
    const content = generateReceipt(info, generatedPacket);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `receipt-${generatedPacket.packetId.slice(0, 8)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Receipt downloaded');
  };

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, delay: 0.05 }}
      >
        <div className="flex items-center gap-3 mb-1">
          <Coins className="h-5 w-5 text-[var(--accent)]" />
          <h1 className="text-lg font-semibold tracking-tight text-[var(--text-primary)]">Send Payment</h1>
        </div>
        <p className="text-[var(--text-secondary)] text-sm ml-8">
          Compose a payment instruction. This simulates an offline client encrypting a payload using the server's public key.
        </p>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-5 gap-8">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.1 }}
          className="md:col-span-3 rounded-lg bg-[var(--bg-card)] p-8 shadow-[0_1px_3px_0_rgba(0,0,0,0.3)]"
        >
          <h2 className="text-xs font-medium text-[var(--text-secondary)] mb-8">Compile Payment</h2>

          <AnimatePresence mode="wait">
            {!generatedPacket || showConfirmation ? (
              !showConfirmation ? (
                <motion.form
                  key="form"
                  onSubmit={handleInject}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 10 }}
                  transition={{ duration: 0.25 }}
                  className="space-y-6"
                >
                  <motion.div
                    variants={staggerContainer}
                    initial="hidden"
                    animate="visible"
                    className="space-y-6"
                  >
                    <motion.div variants={listItem}>
                      <Select
                        label="Sender account"
                        options={VPA_OPTIONS}
                        value={senderVpa}
                        onChange={(e) => setSenderVpa(e.target.value)}
                      />
                    </motion.div>

                    <motion.div variants={listItem}>
                      <Select
                        label="Receiver account"
                        options={VPA_OPTIONS}
                        value={receiverVpa}
                        onChange={(e) => setReceiverVpa(e.target.value)}
                      />
                    </motion.div>

                    <motion.div variants={listItem} className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                      <Input
                        label="Amount (₹)"
                        type="number"
                        value={amount}
                        onChange={(e) => setAmount(e.target.value)}
                        placeholder="Enter amount"
                      />
                      <Input
                        label="UPI PIN"
                        type="password"
                        value={pin}
                        onChange={(e) => setPin(e.target.value)}
                        placeholder="xxxx"
                        maxLength={4}
                      />
                    </motion.div>

                    <motion.div variants={listItem}>
                      <Button
                        type="submit"
                        loading={isSubmitting}
                        className="w-full"
                        size="lg"
                        icon={!isSubmitting ? <Send className="h-4 w-4" /> : undefined}
                      >
                        {isSubmitting ? 'Encrypting envelope...' : 'Inject Payment Packet'}
                      </Button>
                    </motion.div>
                  </motion.div>
                </motion.form>
              ) : (
                <motion.div
                  key="confirmation"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  transition={{ duration: 0.3 }}
                  className="space-y-6 text-center py-4"
                >
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: 'spring', stiffness: 200, damping: 15, delay: 0.1 }}
                    className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[var(--success-subtle)] text-[var(--success)] border-2 border-[var(--success)]/30"
                  >
                    <CheckCheck className="h-10 w-10" />
                  </motion.div>

                  <div>
                    <h3 className="text-base font-semibold text-[var(--text-primary)]">Payment Confirmed</h3>
                    <p className="text-[var(--text-secondary)] text-xs mt-1 font-mono">
                      Successfully processed via QR scan
                    </p>
                  </div>

                  <motion.div
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="rounded-xl border border-[var(--border)] bg-[var(--bg-elevated)] p-4 text-left"
                  >
                    <div className="flex items-center gap-3 mb-3 pb-3 border-b border-[var(--border)]">
                      <div className="text-xl font-semibold text-[var(--success)] font-mono">
                        {formatAmount(parseFloat(amount))}
                      </div>
                      <div className="text-[10px] text-[var(--text-muted)] font-mono ml-auto">
                        {generatedPacket?.injectedAt}
                      </div>
                    </div>
                    <div className="space-y-2 text-xs font-mono">
                      <div className="flex justify-between">
                        <span className="text-[var(--text-muted)]">To:</span>
                        <span className="text-[var(--text-primary)] font-semibold">{receiverVpa}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-[var(--text-muted)]">From:</span>
                        <span className="text-[var(--text-primary)] font-semibold">{senderVpa}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-[var(--text-muted)]">TX ID:</span>
                        <span className="text-[var(--accent)] font-bold text-[10px]">{generatedPacket?.packetId}</span>
                      </div>
                    </div>
                  </motion.div>

                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.3 }}
                    className="space-y-2"
                  >
                    <div className="flex items-center gap-2 text-[11px] text-[var(--success)] font-mono">
                      <CheckCircle className="h-3.5 w-3.5" />
                      Packet encrypted & cached
                    </div>
                    <div className="flex items-center gap-2 text-[11px] text-[var(--success)] font-mono">
                      <CheckCircle className="h-3.5 w-3.5" />
                      QR code scanned & verified
                    </div>
                    <div className="flex items-center gap-2 text-[11px] text-[var(--success)] font-mono">
                      <CheckCircle className="h-3.5 w-3.5" />
                      Injected via {senderVpa}
                    </div>
                  </motion.div>

                  <div className="flex flex-wrap gap-2">
                    <Button
                      variant="secondary"
                      size="sm"
                      icon={<Download className="h-3.5 w-3.5" />}
                      onClick={handleDownloadReceipt}
                      className="flex-1"
                    >
                      Download Receipt
                    </Button>
                    <Button
                      variant="secondary"
                      size="sm"
                      icon={copied ? <CheckCheck className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                      onClick={handleCopyTxId}
                      className="flex-1"
                    >
                      {copied ? 'Copied!' : 'Copy TX ID'}
                    </Button>
                  </div>

                  <Button
                    variant="secondary"
                    size="md"
                    icon={<ArrowLeft className="h-4 w-4" />}
                    onClick={handleResetForm}
                    className="w-full"
                  >
                    Create Another Transaction
                  </Button>
                </motion.div>
              )
            ) : (
              <motion.div
                key="success"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.3 }}
                className="space-y-5 text-center py-4"
              >
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: 'spring', stiffness: 200, damping: 15, delay: 0.1 }}
                  className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[var(--success-subtle)] text-[var(--success)] border border-[var(--success)]/20"
                >
                  <CheckCircle className="h-8 w-8" />
                </motion.div>
                <div>
                  <h3 className="text-sm font-semibold text-[var(--text-primary)]">
                    Packet Injected Successfully
                  </h3>
                  <p className="text-[var(--text-secondary)] text-xs mt-1 font-mono">
                    Envelope generated and cached at {generatedPacket.injectedAt}.
                  </p>
                </div>

                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.15 }}
                  className="flex flex-col items-center gap-2"
                >
                  <div className="relative rounded-xl border-2 border-[var(--border)] bg-white p-3">
                    {qrDataUrl ? (
                      <img
                        src={qrDataUrl}
                        alt="Payment QR Code"
                        className="w-40 h-40 sm:w-44 sm:h-44"
                      />
                    ) : (
                      <div className="w-40 h-40 sm:w-44 sm:h-44 flex items-center justify-center">
                        <QrCode className="h-12 w-12 text-[var(--text-muted)]" />
                      </div>
                    )}
                  </div>
                  <div className="flex items-center gap-1.5 text-[10px] text-[var(--text-muted)] font-mono">
                    <Smartphone className="h-3 w-3" />
                    Scan to process payment
                  </div>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.2 }}
                  className="rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] p-4 text-left text-xs font-mono space-y-2.5"
                >
                  <div className="flex justify-between items-center pb-2 border-b border-[var(--border)]">
                    <span className="text-[var(--text-muted)] text-[10px] uppercase tracking-wider">Payment Summary</span>
                    <span className="text-[var(--success)] font-bold text-sm">
                      {formatAmount(parseFloat(amount))}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[var(--text-muted)]">From:</span>
                    <span className="text-[var(--text-primary)] font-semibold">{senderVpa}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[var(--text-muted)]">To:</span>
                    <span className="text-[var(--text-primary)] font-semibold">{receiverVpa}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[var(--text-muted)]">Packet ID:</span>
                    <span className="text-[var(--accent)] font-bold">{generatedPacket.packetId}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[var(--text-muted)]">Injected:</span>
                    <span className="text-[var(--text-primary)]">{generatedPacket.injectedAt}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[var(--text-muted)]">TTL:</span>
                    <span className="text-[var(--accent)] font-bold">{generatedPacket.ttl} hops</span>
                  </div>
                  <div className="pt-2 border-t border-[var(--border)]">
                    <span className="block text-[var(--text-muted)] mb-1 text-[10px]">Ciphertext (RSA+AES):</span>
                    <div className="bg-[var(--bg-card)] p-2 rounded-lg border border-[var(--border)] select-all overflow-x-auto text-[9px] text-[var(--text-secondary)] whitespace-nowrap">
                      {generatedPacket.ciphertextPreview}
                    </div>
                  </div>
                </motion.div>

                <div className="grid grid-cols-2 gap-2">
                  <Button
                    variant="primary"
                    size="sm"
                    icon={<Smartphone className="h-3.5 w-3.5" />}
                    onClick={handleSimulateScan}
                  >
                    Simulate QR Scan
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    icon={copied ? <CheckCheck className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                    onClick={handleCopyTxId}
                  >
                    {copied ? 'Copied!' : 'Copy TX ID'}
                  </Button>
                </div>

                <Button
                  variant="secondary"
                  size="sm"
                  icon={<Download className="h-3.5 w-3.5" />}
                  onClick={handleDownloadReceipt}
                  className="w-full"
                >
                  Download Payment Receipt
                </Button>

                <Button
                  variant="secondary"
                  size="md"
                  icon={<ArrowLeft className="h-4 w-4" />}
                  onClick={handleResetForm}
                  className="w-full"
                >
                  Create Another Transaction
                </Button>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>

        <div className="md:col-span-2 space-y-5">
          <motion.div
            variants={fadeInRight}
            initial="hidden"
            animate="visible"
            transition={{ duration: 0.4, delay: 0.2 }}
            className="rounded-lg bg-[var(--bg-card)] p-6 shadow-[var(--shadow-md)]"
            style={{ willChange: 'transform, opacity' }}
          >
            <h3 className="font-semibold text-[var(--text-primary)] flex items-center gap-1.5 mb-3 text-sm">
              <Key className="h-4 w-4 text-[var(--accent)]" /> Hybrid Crypto Loop
            </h3>
            <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
              Upon clicking inject, the simulated client pulls the server's cached RSA key, produces a unique transaction key
              via cryptographic randomizer (AES-256), locks the payload JSON with AES-GCM, encrypts the session key under
              RSA-OAEP, and packs them together.
            </p>
          </motion.div>

          <motion.div
            variants={fadeInRight}
            initial="hidden"
            animate="visible"
            transition={{ duration: 0.4, delay: 0.25 }}
            className="rounded-lg bg-[var(--bg-card)] p-6 shadow-[var(--shadow-md)]"
            style={{ willChange: 'transform, opacity' }}
          >
            <h3 className="font-semibold text-[var(--text-primary)] flex items-center gap-1.5 mb-3 text-sm">
              <ShieldAlert className="h-4 w-4 text-[var(--warning)]" /> Offline Balance Validation
            </h3>
            <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
              Notice: The client cannot verify whether the sender possesses sufficient funds while offline. The transaction
              remains in the mesh as an encrypted, deferred IOU. Balance queries and UPI PIN validation only execute once a
              bridge node uploads the envelope to the central gateway database.
            </p>
          </motion.div>
        </div>
      </div>

      <AnimatePresence>
        {showScanner && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"
            onClick={handleCancelScan}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="relative rounded-lg border border-[var(--border)] bg-[var(--bg-card)] p-6 sm:p-8 max-w-sm w-full shadow-2xl"
              onClick={e => e.stopPropagation()}
            >
              <button
                onClick={handleCancelScan}
                className="absolute top-3 right-3 p-1.5 rounded-lg text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-subtle)] transition-colors cursor-pointer"
              >
                <X className="h-4 w-4" />
              </button>

              {!scanComplete ? (
                <>
                  <div className="flex items-center gap-2 mb-6">
                    <Camera className="h-4 w-4 text-[var(--accent)]" />
                    <h3 className="text-xs font-medium text-[var(--text-secondary)]">QR Scanner</h3>
                  </div>

                  <div className="relative mx-auto w-52 h-52 rounded-lg overflow-hidden mb-4 bg-black/90 border-2 border-[var(--border)]">
                    <div className="absolute top-0 left-0 w-6 h-6 border-t-2 border-l-2 border-[var(--accent)] rounded-tl" />
                    <div className="absolute top-0 right-0 w-6 h-6 border-t-2 border-r-2 border-[var(--accent)] rounded-tr" />
                    <div className="absolute bottom-0 left-0 w-6 h-6 border-b-2 border-l-2 border-[var(--accent)] rounded-bl" />
                    <div className="absolute bottom-0 right-0 w-6 h-6 border-b-2 border-r-2 border-[var(--accent)] rounded-br" />

                    <div className="absolute inset-0 flex items-center justify-center">
                      {qrDataUrl && (
                        <img
                          src={qrDataUrl}
                          alt="QR"
                          className="w-32 h-32 opacity-60"
                        />
                      )}
                    </div>

                    <motion.div
                      className="absolute left-2 right-2 h-0.5 bg-[var(--accent)]/50"
                      animate={{ top: ['8%', '92%', '8%'] }}
                      transition={{ duration: 1.8, repeat: Infinity, ease: 'linear' }}
                    />
                  </div>

                  <div className="mb-4">
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-[10px] text-[var(--text-muted)] font-mono flex items-center gap-1">
                        <ScanLine className="h-3 w-3" />
                        Scanning...
                      </span>
                      <span className="text-[10px] font-mono text-[var(--text-muted)]">
                        {Math.round(scanProgress)}%
                      </span>
                    </div>
                    <div className="h-1.5 rounded-full bg-[var(--border)] overflow-hidden">
                      <motion.div
                        className="h-full rounded-full bg-[var(--accent)]"
                        style={{ width: `${scanProgress}%` }}
                        transition={{ duration: 0.3 }}
                      />
                    </div>
                  </div>

                  <p className="text-[10px] text-center text-[var(--text-muted)] font-mono">
                    Align QR code within the frame
                  </p>

                  <Button
                    variant="secondary"
                    size="md"
                    onClick={handleCancelScan}
                    className="w-full mt-4"
                  >
                    Cancel
                  </Button>
                </>
              ) : (
                <div className="py-6 text-center">
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: 'spring', stiffness: 200, damping: 15 }}
                    className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[var(--success-subtle)] text-[var(--success)] border-2 border-[var(--success)]/30 mb-4"
                  >
                    <CheckCircle className="h-10 w-10" />
                  </motion.div>
                  <motion.h3
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.15 }}
                    className="text-sm font-semibold text-[var(--text-primary)]"
                  >
                    QR Code Scanned!
                  </motion.h3>
                  <motion.p
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.25 }}
                    className="text-xs text-[var(--text-secondary)] font-mono mt-1"
                  >
                    Payment of {formatAmount(parseFloat(amount))} to {receiverVpa}
                  </motion.p>
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.35 }}
                    className="flex items-center justify-center gap-2 mt-4 text-[11px] text-[var(--success)] font-mono"
                  >
                    <Clock className="h-3.5 w-3.5" />
                    Processing...
                  </motion.div>
                </div>
              )}
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
export default SendPayment;
